"""Add View more

Revision ID: 913454a865bf
Revises: afa67b8d74f5
Create Date: 2024-10-15 13:42:12.351322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913454a865bf'
down_revision = 'afa67b8d74f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("'000-000-0000'"))
        batch_op.alter_column('additional_images',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('additional_images',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'000-000-0000'"))

    # ### end Alembic commands ###
