"""Add contact info and additional images with default values

Revision ID: afa67b8d74f5
Revises: b3dd71c45b24
Create Date: 2024-10-15 13:00:06.911269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa67b8d74f5'
down_revision = 'b3dd71c45b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'000-000-0000'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("'000-000-0000'"))

    # ### end Alembic commands ###
