"""Add additional_images column to House model

Revision ID: b5894529a922
Revises: cff3d88269ac
Create Date: 2024-10-15 13:57:46.880299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5894529a922'
down_revision = 'cff3d88269ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_images', sa.Text(), nullable=True))
        batch_op.drop_column('house_additional_images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_additional_images', sa.BLOB(), nullable=True))
        batch_op.drop_column('additional_images')

    # ### end Alembic commands ###
