"""Updated house additianal images

Revision ID: cff3d88269ac
Revises: 913454a865bf
Create Date: 2024-10-15 13:52:00.180947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff3d88269ac'
down_revision = '913454a865bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_additional_images', sa.BLOB(), nullable=True))
        batch_op.drop_column('additional_images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_images', sa.TEXT(), nullable=True))
        batch_op.drop_column('house_additional_images')

    # ### end Alembic commands ###
